### PR TITLE
make it use x86 arch

### PR DESCRIPTION
**Pull request by LennyPenny**

### CODE REVIEW

**Comment by sohpeach** [comment]
looks kinda out of place, maybe it belongs in the top part? below the language directive perhaps

**Comment by alexrsagen** [comment]
This will break linux builds. Wrap in an if clause with os.get() == "windows" to fix.

**Comment by sohpeach** [comment]
it'll break linux builds if you don't have 32-bit c++ libs to compile with.

Grab lib32stdc++6

**Comment by alexrsagen** [comment]
Which i have. It breaks regardless.

**Comment by sohpeach** [comment]
update premake5

**Comment by meepen** [comment]
It works fine for me. It won't break anything.

**Comment by sohpeach** [comment]
Older versions of premake accept "x32" and "x64" as architectures (and some other options). This behaviour was deprecated in favour of actual architecture names ("x86" and "x86_64"). So outdated premake is likely the issue here.

@LennyPenny, just chuck the architecture directive underneath the language call and indent it. It'll then be merged.

**Comment by alexrsagen** [comment]
No. x32, x64, x86, x86_64, you name it i've tried and it just says architecture is an invalid option

**Comment by sohpeach** [comment]
```
architecture "x86"
```

This is the part of premake's testing for both visual studio solutions and gmake solutions. That includes msvc, gcc and clang.

**Comment by alexrsagen** [comment]
whatever, don't blame me when my build server refuses to build projects.

**Comment by LennyPenny** [comment]
trin you need install more to make it work
gcc-multilib and smth else, just google around

**Comment by alexrsagen** [comment]
Trust me, i have all the neccesary deps. It works fine without arch setting.

**Comment by LennyPenny** [comment]
@alexrsagen but without the setting they will build as x64 (if your system is x64) and shit wont load in gmod since it needs to be 32 bit

**Pull request merged**
